/** @type {import('tailwindcss').Config} */
// Design system ported from stitch-exports/metis/DESIGN.md (and the Stitch
// inline tailwind config). Operator-console aesthetic: deep teal-tinted
// neutrals, teal #57f1db accent, Inter + JetBrains Mono, 1px borders.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{svelte,ts,js}"],
  theme: {
    extend: {
      colors: {
        background: "#0e1513",
        "on-background": "#dde4e1",
        surface: "#0e1513",
        "surface-dim": "#0e1513",
        "surface-bright": "#333b39",
        "surface-container-lowest": "#09100e",
        "surface-container-low": "#161d1b",
        "surface-container": "#1a211f",
        "surface-container-high": "#242b2a",
        "surface-container-highest": "#2f3634",
        "surface-variant": "#2f3634",
        "surface-tint": "#3cddc7",
        "on-surface": "#dde4e1",
        "on-surface-variant": "#bacac5",
        "inverse-surface": "#dde4e1",
        "inverse-on-surface": "#2b3230",
        outline: "#859490",
        "outline-variant": "#3c4a46",
        primary: "#57f1db",
        "on-primary": "#003731",
        "primary-container": "#2dd4bf",
        "on-primary-container": "#00574d",
        "inverse-primary": "#006b5f",
        "primary-fixed": "#62fae3",
        "primary-fixed-dim": "#3cddc7",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005047",
        secondary: "#9cd1c6",
        "on-secondary": "#003731",
        "secondary-container": "#1a4f47",
        "on-secondary-container": "#8bbfb5",
        "secondary-fixed": "#b8ede2",
        "secondary-fixed-dim": "#9cd1c6",
        "on-secondary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#1a4f47",
        tertiary: "#ffd1aa",
        "on-tertiary": "#4b2800",
        "tertiary-container": "#ffac5a",
        "on-tertiary-container": "#744000",
        "tertiary-fixed": "#ffdcc0",
        "tertiary-fixed-dim": "#ffb875",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6b3b00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        // Functional accents called out in DESIGN.md for tier badges.
        confirm: "#fbbf24",
        highrisk: "#ef4444",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "container-padding": "12px",
        gutter: "8px",
        "component-gap": "4px",
      },
      fontFamily: {
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "mono-md": ["JetBrains Mono", "ui-monospace", "monospace"],
        "mono-sm": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "mono-md": ["13px", { lineHeight: "20px", fontWeight: "450" }],
        "mono-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
