/** @type {import('tailwindcss').Config} */
// Design system: "Obsidian Silk" (stitch-exports-v2/obsidian_silk/DESIGN.md).
// Premium "elevated glassmorphism" — softer charcoal, blue-tinted grays,
// teal #57f1db accent, larger radii, backdrop blur. Color token NAMES match
// the previous theme, so the whole app re-skins from the palette swap.
//
// Typography keeps BOTH the new Obsidian roles AND the prior roles
// (headline-sm/body-md/label-caps/mono-md/mono-sm) so views not yet
// redesigned (Calendar/Email/Files) keep their styling.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{svelte,ts,js}"],
  theme: {
    extend: {
      colors: {
        background: "#111317",
        "on-background": "#e2e2e8",
        surface: "#111317",
        "surface-dim": "#111317",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c20",
        "surface-container": "#1e2024",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "surface-variant": "#333539",
        "surface-tint": "#3cddc7",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#bacac5",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
        outline: "#859490",
        "outline-variant": "#3c4a46",
        primary: "#57f1db",
        "on-primary": "#003731",
        "primary-container": "#2dd4bf",
        "on-primary-container": "#00574d",
        "inverse-primary": "#006b5f",
        "primary-fixed": "#62fae3",
        "primary-fixed-dim": "#3cddc7",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005047",
        secondary: "#bcc7de",
        "on-secondary": "#263143",
        "secondary-container": "#3e495d",
        "on-secondary-container": "#aeb9d0",
        "secondary-fixed": "#d8e3fb",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary-fixed": "#111c2d",
        "on-secondary-fixed-variant": "#3c475a",
        tertiary: "#cadbf5",
        "on-tertiary": "#213145",
        "tertiary-container": "#afbfd9",
        "on-tertiary-container": "#3e4e63",
        "tertiary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#0b1c30",
        "on-tertiary-fixed-variant": "#38485d",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        // Functional tier accents.
        confirm: "#fbbf24",
        highrisk: "#ef4444",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "container-padding": "16px",
        "margin-page": "40px",
        "stack-gap": "12px",
      },
      fontFamily: {
        // Obsidian Silk roles
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Inter", "system-ui", "sans-serif"],
        "title-md": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "label-mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        // Retained prior roles (Calendar/Email/Files views)
        "headline-sm": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
        "mono-md": ["JetBrains Mono", "ui-monospace", "monospace"],
        "mono-sm": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        // Obsidian Silk roles
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-mono": ["13px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "500" }],
        // Retained prior roles
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "mono-md": ["13px", { lineHeight: "20px", fontWeight: "450" }],
        "mono-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
